defaults: &defaults
  adapter: mysql
  host: localhost
  username: root
  password: 

development:
  <<: *defaults
  database: cosa_nostra_development

test:
  adapter: sqlite3
  database: ":memory:"
  timeout: 5000
