defaults: &defaults
  adapter: mysql
  host: localhost
  username: root
  password: 

development:
  <<: *defaults
  database: cosa_nostra_development

test:
  <<: *defaults
  database: cosa_nostra_test
